// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWOTAnalysis.Models;

#nullable disable

namespace SWOTAnalysis.Migrations
{
    [DbContext(typeof(SWOTContext))]
    partial class SWOTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SWOTAnalysis.Models.Oppurtunity", b =>
                {
                    b.Property<int>("OppurtunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OppurtunityId"), 1L, 1);

                    b.Property<string>("OppurtunityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OppurtunityValue")
                        .HasColumnType("int");

                    b.HasKey("OppurtunityId");

                    b.ToTable("Oppurtunities");
                });

            modelBuilder.Entity("SWOTAnalysis.Models.Strength", b =>
                {
                    b.Property<int>("StrengthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StrengthId"), 1L, 1);

                    b.Property<string>("StrengthDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StrengthValue")
                        .HasColumnType("int");

                    b.HasKey("StrengthId");

                    b.ToTable("Strengths");
                });

            modelBuilder.Entity("SWOTAnalysis.Models.SWOT", b =>
                {
                    b.Property<int>("SwotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SwotId"), 1L, 1);

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("OppurtunityId")
                        .HasColumnType("int");

                    b.Property<int>("StrengthId")
                        .HasColumnType("int");

                    b.Property<int>("ThreatId")
                        .HasColumnType("int");

                    b.Property<int>("WeaknessId")
                        .HasColumnType("int");

                    b.HasKey("SwotId");

                    b.HasIndex("OppurtunityId");

                    b.HasIndex("StrengthId");

                    b.HasIndex("ThreatId");

                    b.HasIndex("WeaknessId");

                    b.ToTable("SWOT");
                });

            modelBuilder.Entity("SWOTAnalysis.Models.Threat", b =>
                {
                    b.Property<int>("ThreatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreatId"), 1L, 1);

                    b.Property<string>("ThreatDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThreatValue")
                        .HasColumnType("int");

                    b.HasKey("ThreatId");

                    b.ToTable("Threats");
                });

            modelBuilder.Entity("SWOTAnalysis.Models.Weakness", b =>
                {
                    b.Property<int>("WeaknessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaknessId"), 1L, 1);

                    b.Property<string>("WeaknessDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeaknessValue")
                        .HasColumnType("int");

                    b.HasKey("WeaknessId");

                    b.ToTable("Weaknesses");
                });

            modelBuilder.Entity("SWOTAnalysis.Models.SWOT", b =>
                {
                    b.HasOne("SWOTAnalysis.Models.Oppurtunity", "oppurtunity")
                        .WithMany()
                        .HasForeignKey("OppurtunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWOTAnalysis.Models.Strength", "strength")
                        .WithMany()
                        .HasForeignKey("StrengthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWOTAnalysis.Models.Threat", "threat")
                        .WithMany()
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWOTAnalysis.Models.Weakness", "weakness")
                        .WithMany()
                        .HasForeignKey("WeaknessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("oppurtunity");

                    b.Navigation("strength");

                    b.Navigation("threat");

                    b.Navigation("weakness");
                });
#pragma warning restore 612, 618
        }
    }
}
